#!/usr/bin/env php

<?php
/**
 * Validate commit message and the command content if the commit type is "cmd".
 */

define( 'EOL', "\n" );
echo "commit-msg" . EOL;

function parse_args( $args ) {

    $positional_args = array();
    $assoc_args = array();

    foreach ( $args as $arg ) {
        $positional_arg = null;
        $assoc_arg = null;

        if ( preg_match( '|^--no-([^=]+)$|', $arg, $matches ) ) {
            $assoc_arg = array( $matches[1], false );
        } elseif ( preg_match( '|^--([^=]+)$|', $arg, $matches ) ) {
            $assoc_arg = array( $matches[1], true );
        } elseif ( preg_match( '|^--([^=]+)=(.*)|s', $arg, $matches ) ) {
            $assoc_arg = array( $matches[1], $matches[2] );
        } else {
            $positional_arg = $arg;
        }

        if ( ! is_null( $assoc_arg ) ) {
            $assoc_args[] = $assoc_arg;
        } elseif ( ! is_null( $positional_arg ) ) {
            $positional_args[] = $positional_arg;
        }
    }

    return array( $positional_args, $assoc_args );
}

function validate_wp_cli_command( $command ) {

    $full_args = explode( ' ', $command );
    if ( empty( $full_args ) ) {
        return 'Commit message error: The command is empty';
    }

    $cmd = $full_args[0];
    if ( in_array( $cmd, array( 'new', 'update', 'create' ) ) ) {
        array_shift( $full_args );
        list( $args, $assoc_args ) = parse_args( $full_args );
        if ( empty( $args ) ) {
            return 'Commit message error: The argument is missing in the command';
        }

        if ( $cmd === 'create' || $cmd === 'update' ) {
            $file = $args[0];
            if ( ! is_file( $file ) || ! file_exists( $file ) ) {
                return 'Commit message error: The file argument is wrong. It does not exist';
            }
        }
    }

    return true;
}

$file = $argv[1];
$contents = file_get_contents( $file );
$commit_msg = strstr( $contents, "\n", true ); // First line , the end of line is "\n"

echo 'commit_msg:' . $commit_msg . EOL;

if ( preg_match( '|^([^:]+):\ (.+)$|', $commit_msg, $matches ) ) {
    $commit_type = $matches[1];

    if( $commit_type === 'cmd' ) {
        $command = $matches[2];
        $result = validate_wp_cli_command( $command );
        if ( $result !== true ) {
            echo( $result . EOL );
            exit( 1 );
        }
    }

    exit( 0 );
}

echo 'Commit message error: The format is not correct, it must be <commit-type>: <commit-message>' . PHP_EOL;
exit( 1 );
